/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
*/
  const express = require('express');
  const bodyParser = require('body-parser');
  
  const app = express();
  app.use(bodyParser.json());
  app.use(express.json());

  const fs = require('fs').promises;

  async function readFile() {
    try {
      let data = await fs.readFile('todos.json', 'utf-8');
      return JSON.parse(data);
    } 
    catch(err) {
      console.error(err);
      return false;
    }
  }

  async function writeFile(data) {
    try {
      await fs.writeFile('todos.json', JSON.stringify(data, null, 2));
    } catch (err) {
      console.error(err);
    }
  }

  app.get('/todos', async (req, res) => {
    const data = await readFile();
    
    if (!data) {
      return res.status(500).json({ error: "Failed to read todos" });
    }
    res.status(200).json(data)
  })

  app.get('/todos/:id', async (req, res) => {
    const data = await readFile();
    const id = Number(req.params.id);

    let todo = data.find(todo => todo.id === id);
    
    if (todo !== undefined) {
      res.status(200).json(todo)
    } else {
      res.status(404).json({ error: "Not Found" });
    }
  })

  app.post('/todos', async (req, res) => {
    let fileData = await readFile();
    if (fileData) {
      let data = req.body;
      let idCounter = fileData.length > 0 ? Math.max(...fileData.map(t => t.id)): 0;
      let todo = {
        id: idCounter+1,
        title: data.title,
        description: data.description
      }
      fileData.push(todo);
      await writeFile(fileData);
      res.status(201).json({ id: todo.id });
    } else {
      res.status(404).json({ error: "Database error" })
    }
  })

  app.delete('/todos/:id', async (req, res) => {
    let fileData = await readFile();
    const id = Number(req.params.id);
    if (fileData) {
      if (fileData.find(t => t.id === id)) {
        fileData = fileData.filter(t => t.id !== id)
        await writeFile(fileData);
        res.status(200).json({ status: "DELETED" });
      } else {
        res.status(404).json({ error: "Not Found" });
      }
    } else {
      res.status(404).json({ error: "Database error" })
    }
  })

  app.put('/todos/:id', async (req, res) => {
    let fileData = await readFile();
    let id = Number(req.params.id);
    if (fileData) {
      let index = fileData.findIndex(t => t.id === id);
      if (index < 0) {
        res.status(404).json({ error: "Not Found" });
      } else {
        fileData[index].title = req.body.title;
        fileData[index].description = req.body.description;
        await writeFile(fileData);
        res.status(200).json({ status: "OK"})
      }
    } else {
      res.status(404).json({ error: "Database error" })
    }
  })

  module.exports = app;